#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

indx=0
while ((indx < 10));
do
	if [ $indx -eq 3 ];
	then
		echo "bad luck"

	elif [ $indx -eq 7 ];
	then
		echo "good luck"

	else
		echo "Best School"
	fi;
	((indx++));
done;