#!/usr/bin/env bash
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

LIST=$(ls)
for file in $LIST;
do
	echo "$file" | cut -d'-' -f2;
done;